### ISSUE TITLE
[ng:btstrpd] App Already Bootstrapped with this Element 'document'

### ISSUE THREAD

**Issue by jeangui** [netanelgilad/meteor-ionic-example#9] opened 2015-02-27 16:23 UTC
Hello,

I am trying to run this sample on my mac and I am getting the following error when I run `meteor`.

`Error: [ng:btstrpd] App Already Bootstrapped with this Element 'document'
http://errors.angularjs.org/1.3.14/ng/btstrpd?p0=document
    at http://localhost:3000/packages/angularjs_angular.js?cd6b2d01f519ab80a987d88280d8bede8e8da8c1:93:14`

It seems that this kind of error happens when ng-app and the angular bootstrap are used simultanously (ref: https://docs.angularjs.org/error/ng/btstrpd).

> This usually happens when you accidentally use both ng-app and angular.bootstrap to bootstrap an application.

but I don't any use of ng-app.

Best Regards,

@jeangui

**Comment by minheq** [comment] 2015-03-10 19:15
I believe this has been caused by the update with one of the dependencies, possibly 1.0.3.2 meteor update. I encountered the same issue as u did after updating this project dependencies

**Comment by ambujpunn** [comment] 2015-04-02 06:14
I seem to have the same issue: https://github.com/netanelgilad/meteor-ionic-example/issues/10

**Comment by AhmadEl-Banna** [comment] 2015-04-05 20:31
the project was working before i move the files to client and server and the same error occurred

**Comment by AhmadEl-Banna** [comment] 2015-04-05 20:44
I didn't update any thing and I got the same error

**Comment by elmor34** [comment] 2015-04-06 01:51
I 've solved the problem. Now it works with the latesr version 1.1.
Only urigo:ionic and urigo:angular need to be added.
Changed :

Packages to :
```
meteor-platform
urigo:ionic
urigo:angular
```
and app bootstrap to :
```
    Meteor.startup(function ()
    {
      angular.bootstrap(document, ['starter']);
    });

angular.module('starter', ['angular-meteor','ionic', 'starter.controllers'])

.run(['$ionicPlatform',function($ionicPlatform) {
  $ionicPlatform.ready(function() {
    // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
    // for form inputs)
    if(window.cordova && window.cordova.plugins.Keyboard) {
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
    }
    if(window.StatusBar) {
      // org.apache.cordova.statusbar required
      StatusBar.styleDefault();
    }
  });
}])
```

**Comment by netanelgilad** [comment] 2015-04-06 06:45
Should be fixed with my new updates.
check it out and reopen if this still happens.

**Closed by netanelgilad** 2015-04-06 06:45 UTC

**Comment by elmor34** [comment] 2015-04-06 06:51
Thanks. Happy end.

Gokhan from Istambul

On Mon, Apr 6, 2015 at 9:45 AM, Netanel Gilad <notifications@github.com>
wrote:

> Should be fixed with my new updates.
> check it out and reopen if this still happens.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/netanelgilad/meteor-ionic-example/issues/9#issuecomment-89947338>
> .
>



-- 
Gokhan AYKAN
